/**
 * Shop catalog — matches api/shop.php and store sprite sheets
 */
const SHOP_CATALOG = {
  skins: [
    { id: 'skin_fire', name: { en: 'Fire Power', zh: '烈火威力' }, price: 200, grid: [0, 0],
      desc: { en: 'An iconic red and white outfit that radiates intense heat.', zh: '经典的红白配色，散发着强烈的热量。' } },
    { id: 'skin_snow', name: { en: 'Snow Land', zh: '冰雪世界' }, price: 250, grid: [1, 0],
      desc: { en: 'A frosty, cool outfit built for sub-zero temperatures.', zh: '专为严寒打造的冰爽冬装。' } },
    { id: 'skin_green', name: { en: 'Classic Green', zh: '经典之绿' }, price: 300, grid: [2, 0],
      desc: { en: 'The ultimate Player 2 attire.', zh: '终极的2号玩家套装。' } },
    { id: 'skin_vintage', name: { en: 'Vintage B&W', zh: '复古黑白' }, price: 150, grid: [0, 1],
      desc: { en: 'Travel back in time with this classic look.', zh: '穿上这款复古怀旧的外观，瞬间穿越回过去。' } },
    { id: 'skin_default', name: { en: 'Original', zh: '泡泡糖粉' }, price: 0, grid: [1, 1],
      desc: { en: 'Default bubblegum factory look.', zh: '默认的泡泡糖工厂外观。' } },
    { id: 'skin_star', name: { en: 'Star-Power', zh: '无敌星光' }, price: 999, grid: [2, 1],
      desc: { en: 'A brilliant flashing skin. Invincibility is psychological only.', zh: '模拟无敌状态的耀眼闪光皮肤。' } },
    { id: 'skin_neon', name: { en: 'Neon Cyber', zh: '霓虹赛博' }, price: 450, grid: [0, 2],
      desc: { en: 'A futuristic glowing outfit.', zh: '专为数字天堂设计的未来感发光套装。' } },
    { id: 'skin_zombie', name: { en: 'Zombie', zh: '丧尸复生' }, price: 400, grid: [1, 2],
      desc: { en: 'A spooky undead look.', zh: '专为永不言弃的玩家打造的不死族外观。' } },
    { id: 'skin_cosmic', name: { en: 'Cosmic Space', zh: '浩瀚宇宙' }, price: 500, grid: [2, 2],
      desc: { en: 'Forged from stars and nebulas.', zh: '由繁星、星云和无尽虚空锻造而成。' } },
  ],
  trails: [
    { id: 'trail_glitter', name: { en: 'Sweet Glitter', zh: '甜心闪粉' }, price: 120 },
    { id: 'trail_bubble', name: { en: 'Bubble Trail', zh: '泡泡跟随' }, price: 100 },
    { id: 'trail_wrappers', name: { en: 'Candy Wrappers', zh: '糖果包装纸' }, price: 80 },
  ],
  splats: [
    { id: 'splat_confetti', name: { en: 'Confetti Splat', zh: '彩纸爆炸' }, price: 90 },
    { id: 'splat_ooze', name: { en: 'Toxic Ooze', zh: '毒液飞溅' }, price: 110 },
    { id: 'splat_gold', name: { en: 'Gold Glitter', zh: '金粉爆炸' }, price: 150 },
  ],
  snacks: [
    { id: 'snack_bullet', name: { en: 'Bullet Bill Bits', zh: '炮弹刺客碎碎糖' }, price: 25, goodsRow: 3, goodsCol: 1,
      desc: { en: "Tiny candy pellets shaped like the kingdom's fastest projectiles. Eating them gives you exactly zero speed boosts, but they do make a tiny 'pew pew' sound in your mouth.",
        zh: '外形酷似王国最快飞弹的微型碎碎糖。吃掉它们不会给你任何速度加成，但它们确实会在你嘴里发出微小的「咻咻」声。' } },
    { id: 'snack_block', name: { en: 'Block Powder', zh: '砖块糖粉' }, price: 20, goodsRow: 4, goodsCol: 1,
      desc: { en: "A packet of crushed candy dust that tastes like nostalgia and gravel. It won't help you smash real blocks, but it will leave a colorful smudge on your face.",
        zh: '一包碎糖粉，尝起来有种怀旧和碎石的味道。它帮不了你砸碎现实中的砖块，但绝对会在你脸上留下一抹滑稽的色彩。' } },
    { id: 'snack_waffle', name: { en: 'Warp Pipe Waffles', zh: '传送管道华夫饼' }, price: 30, goodsRow: 4, goodsCol: 2,
      desc: { en: "Bright green, grid-patterned waffles. They don't transport you to a hidden coin heaven—they just teleport straight into your stomach. Deliciously useless!",
        zh: '鲜绿色的网格华夫饼。它们不会把你传送到隐藏的金币天堂——只会直接传送进你的肚子里。美味得毫无用处！' } },
    { id: 'snack_locket', name: { en: 'Power Locket', zh: '力量糖果吊坠' }, price: 35, goodsRow: 2, goodsCol: 1,
      desc: { en: 'A shiny candy locket filled with sweet powder. It looks like a legendary quest item, but its only real power is making your character look incredibly fancy while eating it.',
        zh: '一个亮晶晶、装满甜粉的糖果吊坠。它看起来像个传说中的任务道具，但它唯一真正的力量，就是让你的角色在吃它时显得格外高贵。' } },
    { id: 'snack_goomba', name: { en: 'Goomba Gummies', zh: '栗宝宝软糖' }, price: 28, goodsRow: 2, goodsCol: 2,
      desc: { en: "Chewy, dome-shaped gummies modeled after everyone's favorite walking mushroom. You get to squash them with your teeth instead of your boots for a change.",
        zh: 'Q弹的圆顶软糖，模仿了大家最爱的走路菇。这次你可以用牙齿代替靴子来踩扁它们了。' } },
    { id: 'snack_flower', name: { en: 'Fire Flower', zh: '火之花糖' }, price: 32, goodsRow: 2, goodsCol: 0,
      desc: { en: "A spicy-sweet confectionary flower. It doesn't grant you the ability to shoot fireballs at enemies, but it will make your character puff a harmless cloud of smoke from their ears.",
        zh: '一朵又辣又甜的糖果花。它不会赋予你向敌人发射火球的能力，但它会让你的角色耳朵里冒出一缕无害的烟雾。' } },
    { id: 'snack_soda', name: { en: 'Flower Soda', zh: '花卉苏打' }, price: 22, goodsRow: 1, goodsCol: 0,
      desc: { en: 'A fizzy, floral beverage that sparkles under the sky. Chugging it down rewards you with a massive, echoey burp that shakes the camera for a split second.',
        zh: '一种在天空下闪闪发光的起泡花卉饮料。一饮而尽后，你会获得一声响亮、带回音的巨响饱嗝，让镜头瞬间震动一下。' } },
    { id: 'snack_yoshi', name: { en: "Yoshi's Drink", zh: '耀西特调' }, price: 26, goodsRow: 0, goodsCol: 2,
      desc: { en: "A bright green juice box that tastes faintly of melons and adventure. It doesn't give you a giant tongue to swallow enemies, but it does leave a neon green mustache on your face.",
        zh: '一个鲜绿色的果汁盒，隐约有种甜瓜和冒险的味道。它不会给你一条吞噬敌人的大舌头，但确实会在你嘴上留下一圈霓虹绿的胡子。' } },
    { id: 'snack_pasta', name: { en: "Bowser's Fire Pasta", zh: '库巴烈火面' }, price: 40, goodsRow: 1, goodsCol: 3,
      desc: { en: 'A cup of intensely spicy, red-hot noodles. Eating this causes your character to frantically run in small circles while panting. A great way to waste time before getting trolled.',
        zh: '一碗超级无敌辣的红热面条。吃下它会让你的角色一边哈气一边疯狂地原地转圈。在被陷阱坑死之前，这真是个绝佳的消磨时间法。' } },
    { id: 'snack_mushroom', name: { en: 'Super Mushroom', zh: '超级蘑菇糖' }, price: 50, goodsRow: 0, goodsCol: 0,
      desc: { en: "The most iconic treat in the realm! Unfortunately, this version doesn't make you grow twice your size or absorb a hit. It's literally just regular candy. Enjoy the placebo effect!",
        zh: '王国里最具标志性的零食！可惜这个版本既不能让你体型变大两倍，也不能替你挡一下。它就是普通的糖果。请享受安慰剂效应吧！' } },
    { id: 'snack_star', name: { en: 'Star Candy', zh: '星星糖' }, price: 45, goodsRow: 1, goodsCol: 2,
      desc: { en: "A glowing, star-shaped hard candy. It doesn't grant temporary invincibility, nor does it play cool music. It just tastes pretty good and sparkles in the dark.",
        zh: '一颗闪闪发光的星形硬糖。它既不能让你无敌，也不会播放酷炫的背景音乐。它只是味道不错，而且会在黑暗中闪烁。' } },
    { id: 'snack_shy', name: { en: 'Shy Guy Syrup', zh: '嘿呵糖浆' }, price: 24, goodsRow: 4, goodsCol: 3,
      desc: { en: 'A sweet, mysterious syrup. Drinking it makes your character let out a tiny, high-pitched Shy Guy squeak. Completely unhelpful for platforming, but highly adorable.',
        zh: '一种甜蜜又神秘的糖浆。喝下它会让你的角色发出微小、高亢的嘿呵叫声。对平台跳跃毫无帮助，但极其可爱。' } },
  ],
  tricks: [
    { id: 'fake_star', name: { en: '??? Super Star', zh: '??? 超级星星' }, price: 500,
      desc: { en: 'Surely this legendary item will help...', zh: '这传说级道具肯定有用……吧？' } },
    { id: 'mute_dev', name: { en: 'Mute the Developer', zh: '静音开发者' }, price: 150,
      desc: { en: 'Silence mocking laugh on death.', zh: '死亡时不再听到嘲讽笑声。' } },
  ],
};

const SKIN_TINTS = {
  skin_default: null,
  skin_fire: '#ff3333',
  skin_snow: '#66ccff',
  skin_green: '#33cc33',
  skin_vintage: '#888888',
  skin_star: '#ffd700',
  skin_neon: '#00ffff',
  skin_zombie: '#6b8f5e',
  skin_cosmic: '#6633cc',
};

window.SHOP_CATALOG = SHOP_CATALOG;
window.SKIN_TINTS = SKIN_TINTS;
